version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - ./build-tools/run_pre_build.sh
  build:
    commands:
      - ./build-tools/run_build.sh
  post_build:
    commands:
      - echo Build completed on `date`
