name: Build
on:
  push:
    branches:
      - develop
      - master
      - ms2.0/qa
      - ms2.0/github-build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: configure git
        run: git config --global init.defaultBranch master
      - name: clone medshorts-web
        uses: actions/checkout@v2
        with:
          repository: medshorts-llc/medshorts-web
          path: ./
          ref: ${{ github.head_ref }}
          ssh-key: ${{ secrets.ORG_SSH_KEY }}
          persist-credentials: true

      - name: clone build-tools
        uses: actions/checkout@v2
        with:
          repository: medshorts-llc/build-tools
          path: ./build-tools
          ref: github
          ssh-key: ${{ secrets.ORG_SSH_KEY }}
          persist-credentials: true

      - name: Build
        run: | 
          export AWS_DEFAULT_REGION=us-west-2
          export AWS_ACCESS_KEY_ID=${{ secrets.ORG_AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.ORG_AWS_SECRET_ACCESS_KEY }}
          chmod +x ./build-tools/run_pre_build.sh
          chmod +x ./build-tools/run_build.sh
          chmod +x ./build/build.sh
          chmod +x ./build/deploy.sh
          ./build-tools/run_pre_build.sh
          ./build-tools/run_test.sh
          ./build-tools/run_build.sh
